import sys
from PyQt6.QtWidgets import QApplication, QWidget,  QFormLayout, QVBoxLayout, QHBoxLayout, QGridLayout, QTabWidget, QLineEdit, QDateEdit, QPushButton, QTextEdit, QGroupBox, QLabel, QSpinBox, QCheckBox
from PyQt6.QtCore import Qt
from ApdcamUtils import *


class ControlTiming(QWidget):
    def __init__(self,parent):
        super(ControlTiming,self).__init__(parent)
        layout = QHBoxLayout()
        self.setLayout(layout)

        l = QVBoxLayout()
        layout.addLayout(l)

        g = QHGroupBox("CC card temperatures")
        l.addWidget(g)
        g.addWidget(QLabel("CC card temp.:"))
        self.ccCardTemp = QDoubleEdit()
        g.addWidget(self.ccCardTemp)
        g.addWidget(QLabel("CC card max. temp.:"))
        self.ccCardMaxTemp = QDoubleEdit()
        g.addWidget(self.ccCardMaxTemp)

        g = QGridGroupBox("CC card voltages")
        l.addWidget(g)
        g.addWidget(QLabel("3.3 V:"),0,0)
        self.ccCardVoltage33 = QDoubleEdit()
        g.addWidget(self.ccCardVoltage33,0,1)
        g.addWidget(QLabel("1.8 V XC:"),0,2)
        self.ccCardVoltage18XC = QDoubleEdit()
        g.addWidget(self.ccCardVoltage18XC,0,3)
        g.addWidget(QLabel("2.5 V:"),1,0)
        self.ccCardVoltage25 = QDoubleEdit()
        g.addWidget(self.ccCardVoltage25,1,1)
        g.addWidget(QLabel("1.2 V ST:"),1,2)
        self.ccCardVoltage12ST = QDoubleEdit()
        g.addWidget(self.ccCardVoltage12ST,1,3)

        g = QGridGroupBox()
        l.addWidget(g)
        g.addWidget(QLabel("Base PLL Mult.:"),0,0)
        self.basePllMult = QSpinBox()
        g.addWidget(self.basePllMult,0,1)
        g.addWidget(QLabel("Div.:"),0,2)
        self.basePllDiv = QSpinBox()
        g.addWidget(self.basePllDiv,0,3)
        g.addWidget(QLabel("Serial PLL Mult.:"),1,0)
        self.serialPllMult = QSpinBox()
        g.addWidget(self.serialPllMult,1,1)
        g.addWidget(QLabel("Div.:"),1,2)
        self.serialPllDiv = QSpinBox()
        g.addWidget(self.serialPllDiv,1,3)
        g.addWidget(QLabel("EXT CLK Mult.:"),2,0)
        self.extClockMult = QSpinBox()
        g.addWidget(self.extClockMult,2,1)
        g.addWidget(QLabel("Div.:"),2,2)
        self.extClockDiv = QSpinBox()
        g.addWidget(self.extClockDiv,2,3)
        g.addWidget(QLabel("Sample Div.:"),3,0)
        self.sampleDiv = QSpinBox()
        g.addWidget(self.sampleDiv,3,1)
        g.setRowStretch(g.rowCount(),1)

        l.addStretch(1)

        self.readFromHwButton = QPushButton("Read from HW")
        l.addWidget(self.readFromHwButton)


        l = QVBoxLayout()
        layout.addLayout(l)

        g = QGridLayout()
        l.addLayout(g)
        g.addWidget(QLabel("ADC freq. [MHz]:"),0,0)
        self.adcFrequency = QSpinBox()
        g.addWidget(self.adcFrequency,0,1)
        g.addWidget(QLabel("SATA freq. [MHz]:"),1,0)
        self.sataFrequency = QSpinBox()
        g.addWidget(self.sataFrequency,1,1)

        g = QVGroupBox()
        l.addWidget(g)
        self.adcClockExt = QCheckBox("ADC Clock Ext.")
        g.addWidget(self.adcClockExt)
        self.autoExtClock = QCheckBox("Auto Ext. Clock")
        g.addWidget(self.autoExtClock)
        self.extSample = QCheckBox("Ext. Sample")
        g.addWidget(self.extSample)
        
        g = QVGroupBox()
        l.addWidget(g)
        self.basicPllLocked = QCheckBox("Basic PLL Locked")
        g.addWidget(self.basicPllLocked)
        self.sataPllLocked = QCheckBox("SATA PLL Locked")
        g.addWidget(self.sataPllLocked)
        self.extDcmLocked = QCheckBox("Ext. DCM Locked")
        g.addWidget(self.extDcmLocked)
        self.extClockValid = QCheckBox("Ext. Clock Valid")
        g.addWidget(self.extClockValid)
        h = QHBoxLayout()
        g.addLayout(h)
        h.addWidget(QLabel("Ext. clock freq. [MHz]"))
        self.extClockFrequency = QSpinBox()
        h.addWidget(self.extClockFrequency)

        l = QVBoxLayout()
        layout.addLayout(l)

        self.dualSata = QCheckBox("Dual SATA")
        self.dualSata.factorySetting = True
        l.addWidget(self.dualSata)

        g = QVGroupBox()
        l.addWidget(g)
        self.trigPlus = QCheckBox("Trig +")
        g.addWidget(self.trigPlus)
        self.trigMinus = QCheckBox("Trig -")
        g.addWidget(self.trigMinus)
        self.maxTrig = QCheckBox("Max. trig.")
        g.addWidget(self.maxTrig)
        self.disableWhenStreamOff = QCheckBox("Disable when stream off")
        g.addWidget(self.disableWhenStreamOff)
        h = QHBoxLayout()
        g.addLayout(h)
        h.addWidget(QLabel("Trigger delay [\u03bcs]:"))
        self.triggerDelay = QSpinBox()
        h.addWidget(self.triggerDelay)

        h = QHBoxLayout()
        l.addLayout(h)
        h.addWidget(QLabel("Sample number: "))
        self.sampleNumber = QSpinBox()
        h.addWidget(self.sampleNumber)

        layout.addStretch(1)
