#ifndef __CCREGS_H__

#define __CCREGS_H__

#define CC_DIT_TABLE          0
#define CC_SETTINGS_TABLE     1
#define CC_DIT_SETTINGS_TABLE 2
#define CC_VARIABLES_TABLE    3

#define ACKANSWER_HEADER_LEN  7

//10G Settings and Variables Registers
#define CC_DEVICE_TYPE     (56 - ACKANSWER_HEADER_LEN)
#define CC_DEVICE_TYPE_LEN 2

#define CC_STREAM_SERIAL     (58 - ACKANSWER_HEADER_LEN)
#define CC_STREAM_SERIAL_LEN 4

#define CC_REG_CLOCK_CONTROL     (263 - ACKANSWER_HEADER_LEN)
#define CC_REG_CLOCK_CONTROL_LEN 1

#define CC_REG_CLOCK_ENABLE     (264 - ACKANSWER_HEADER_LEN)
#define CC_REG_CLOCK_ENABLE_LEN 1

#define CC_REG_SATACONTROL      (292 - ACKANSWER_HEADER_LEN)
#define CC_REG_SATACONTROL_LEN  1

#define CC_REG_BASICPLL_MUL     (265 - ACKANSWER_HEADER_LEN)
#define CC_REG_BASICPLL_MUL_LEN 1

#define CC_REG_BASICPLL_DIV0     (266 - ACKANSWER_HEADER_LEN)
#define CC_REG_BASICPLL_DIV0_LEN 1

#define CC_REG_BASICPLL_DIV1     (267 - ACKANSWER_HEADER_LEN)
#define CC_REG_BASICPLL_DIV1_LEN 1

#define CC_REG_BASICPLL_DIV2     (268 - ACKANSWER_HEADER_LEN)
#define CC_REG_BASICPLL_DIV2_LEN 1

#define CC_REG_BASICPLL_DIV3     (269 - ACKANSWER_HEADER_LEN)
#define CC_REG_BASICPLL_DIV3_LEN 1

#define CC_REG_BASICPLL      CC_REG_BASICPLL_MUL
#define CC_REG_BASICPLL_LEN  (CC_REG_BASICPLL_MUL_LEN + CC_REG_BASICPLL_DIV0_LEN + CC_REG_BASICPLL_DIV1_LEN + CC_REG_BASICPLL_DIV2_LEN + CC_REG_BASICPLL_DIV3_LEN)

#define CC_REG_EXTDCM_MUL     (270 - ACKANSWER_HEADER_LEN)
#define CC_REG_EXTDCM_MUL_LEN 1

#define CC_REG_EXTDCM_DIV     (271 - ACKANSWER_HEADER_LEN)
#define CC_REG_EXTDCM_DIV_LEN 1

#define CC_REG_EXTDCM      CC_REG_EXTDCM_MUL
#define CC_REG_EXTDCM_LEN  (CC_REG_EXTDCM_MUL_LEN + CC_REG_EXTDCM_DIV_LEN)

#define CC_REG_SAMPLEDIV     (272 - ACKANSWER_HEADER_LEN)
#define CC_REG_SAMPLEDIV_LEN 2

#define CC_REG_SAMPLECOUNT     (276 - ACKANSWER_HEADER_LEN)
#define CC_REG_SAMPLECOUNT_LEN 6

#define CC_REG_TRIGGER_CONTROL     (282 - ACKANSWER_HEADER_LEN)
#define CC_REG_TRIGGER_CONTROL_LEN 1

#define CC_REG_TRIGGER_DELAY     (283 - ACKANSWER_HEADER_LEN)
#define CC_REG_TRIGGER_DELAY_LEN 4

#define CC_REG_TRIGGER     CC_REG_TRIGGER_CONTROL
#define CC_REG_TRIGGER_LEN (CC_REG_TRIGGER_CONTROL_LEN + CC_REG_TRIGGER_DELAY_LEN)

#define CC_REG_STREAM_CONTROL     (299 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_CONTROL_LEN 1

#define CC_REG_STREAM_1_OCTET         (311 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_1_OCTET_LEN     2
#define CC_REG_STREAM_1_MAC           (313 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_1_MAC_LEN       6
#define CC_REG_STREAM_1_IP            (319 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_1_IP_LEN        4
#define CC_REG_STREAM_1_PORT          (323 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_1_PORT_LEN      2
#define CC_REG_STREAM_1               (CC_REG_STREAM_1_OCTET)
#define CC_REG_STREAM_1_LEN           (CC_REG_STREAM_1_OCTET_LEN + CC_REG_STREAM_1_MAC_LEN + CC_REG_STREAM_1_IP_LEN + CC_REG_STREAM_1_PORT_LEN)

#define CC_REG_STREAM_2_OCTET         (327 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_2_OCTET_LEN     2
#define CC_REG_STREAM_2_MAC           (329 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_2_MAC_LEN       6
#define CC_REG_STREAM_2_IP            (335 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_2_IP_LEN        4
#define CC_REG_STREAM_2_PORT          (339 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_2_PORT_LEN      2
#define CC_REG_STREAM_2               (CC_REG_STREAM_2_OCTET)
#define CC_REG_STREAM_2_LEN           (CC_REG_STREAM_2_OCTET_LEN + CC_REG_STREAM_2_MAC_LEN + CC_REG_STREAM_2_IP_LEN + CC_REG_STREAM_2_PORT_LEN)

#define CC_REG_STREAM_3_OCTET         (343 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_3_OCTET_LEN     2
#define CC_REG_STREAM_3_MAC           (345 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_3_MAC_LEN       6
#define CC_REG_STREAM_3_IP            (351 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_3_IP_LEN        4
#define CC_REG_STREAM_3_PORT          (355 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_3_PORT_LEN      2
#define CC_REG_STREAM_3               (CC_REG_STREAM_3_OCTET)
#define CC_REG_STREAM_3_LEN           (CC_REG_STREAM_3_OCTET_LEN + CC_REG_STREAM_3_MAC_LEN + CC_REG_STREAM_3_IP_LEN + CC_REG_STREAM_3_PORT_LEN)

#define CC_REG_STREAM_4_OCTET         (359 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_4_OCTET_LEN     2
#define CC_REG_STREAM_4_MAC           (361 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_4_MAC_LEN       6
#define CC_REG_STREAM_4_IP            (367 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_4_IP_LEN        4
#define CC_REG_STREAM_4_PORT          (371 - ACKANSWER_HEADER_LEN)
#define CC_REG_STREAM_4_PORT_LEN      2
#define CC_REG_STREAM_4               (CC_REG_STREAM_4_OCTET)
#define CC_REG_STREAM_4_LEN           (CC_REG_STREAM_4_OCTET_LEN + CC_REG_STREAM_4_MAC_LEN + CC_REG_STREAM_4_IP_LEN + CC_REG_STREAM_4_PORT_LEN)

#define CC_REG_VAR_SAMPLE_COUNTER_x_LEN  6
#define CC_REG_VAR_SAMPLE_COUNTER_1      (305 - ACKANSWER_HEADER_LEN)
#define CC_REG_VAR_SAMPLE_COUNTER_1_LEN  CC_REG_VAR_SAMPLE_COUNTER_x_LEN
#define CC_REG_VAR_SAMPLE_COUNTER_2      (311 - ACKANSWER_HEADER_LEN)
#define CC_REG_VAR_SAMPLE_COUNTER_2_LEN  CC_REG_VAR_SAMPLE_COUNTER_x_LEN
#define CC_REG_VAR_SAMPLE_COUNTER_3      (317 - ACKANSWER_HEADER_LEN)
#define CC_REG_VAR_SAMPLE_COUNTER_3_LEN  CC_REG_VAR_SAMPLE_COUNTER_x_LEN
#define CC_REG_VAR_SAMPLE_COUNTER_4      (323 - ACKANSWER_HEADER_LEN)
#define CC_REG_VAR_SAMPLE_COUNTER_4_LEN  CC_REG_VAR_SAMPLE_COUNTER_x_LEN
#define CC_REG_VAR_SAMPLE_COUNTER        CC_REG_VAR_SAMPLE_COUNTER_1
#define CC_REG_VAR_SAMPLE_COUNTER_LEN    (CC_REG_VAR_SAMPLE_COUNTER_x_LEN * 4)

#endif  /* __CCREGS_H__ */
